- .gitignore
- index.html
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
초기 설정
resolves #1
> init : 초기환경구성

- index.html
- src/components/main-button/main-button.css
- src/components/main-button/main-button.html
- src/style.css
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #17
> feature - 바로가기 링크 컴포넌트 마크업 및 스타일링 구현 완료

- src/components/total-statistics/total-statistics.css
- src/components/total-statistics/total-statistics.html
- src/components/total-statistics/total-statistics.js
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #24
> feat: 전적 통계 컴포넌트 API 연동

- index.html
- src/components/score-info/score-info.css
- src/components/score-info/score-info.html
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #26
> feat:전적 페이지 안내 컴포넌트 마크업 및 구현

- src/components/footer/footer.js
- src/components/header/header.html
- src/components/header/header.js
- src/components/main-button/main-button.html
- src/components/main-visual/main-visual.html
- src/components/main-visual/main-visual.js
- src/components/score-info/score-info.html
- src/components/team-introduction/team-introduction.css
- src/components/team-introduction/team-introduction.html
- src/components/team-introduction/team-introduction.js
- src/components/total-statistics/total-statistics.html
- src/components/total-statistics/total-statistics.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #36
> accessibility: 메인 버튼 컴포넌트 마크업 수정 완료

- src/components/score-detail/score-detail.css
- src/components/score-detail/score-detail.html
- src/components/score-detail/score-detail.js
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
전적 리스트 구현
resolves #8
> feat - 전적 리스트 구현

- src/components/footer/footer.css
- src/components/footer/footer.html
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #48
> design: 푸터 컴포넌트 CSS 수정 완료

- src/components/otherinfo/other-Info.css
- src/components/otherinfo/other-info.js
- src/components/userinfo/user-Info.css
- src/components/userinfo/user-Info.js
- src/data/rank_tier_Response.json
- src/data/season_grade_Response.json
- src/data/total_grade_Response.json
- src/style.css
- src/utils/date.js
- [] 버그 수정
- [] 코드 리팩토링
resolves #52
> feat - 유저 정보 UI 병합 및 기능 작성 #52

- netlify.toml
- netlify/functions/api-proxy.js
- src/components/live/live.js
- [] 새로운 기능 추가
- [] 문서 수정
resolves #57
> fix - 치지직 라이브 컴포넌트 api통신 500에러 수정

- src/components/total-statistics/total-statistics.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #60
> refactor : total-statistics 컴포넌트 템플릿 리터럴 방식 수정 완료

- src/components/score-info/score-info.js
- src/components/total-statistics/total-statistics.css
- src/components/total-statistics/total-statistics.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #62
> design : total-statistics 컴포넌트 폰트 수정 완료

- src/components/convention/convention.html
- src/components/convention/convention.js
- src/components/home/home.css
- src/components/home/home.html
- src/components/home/home.js
- src/components/live/live.css
- src/components/main-visual/main-visual.html
- src/components/main-visual/main-visual.js
- src/components/news/news.css
- src/components/news/news.js
- src/components/record/record.css
- src/components/record/record.html
- src/components/record/record.js
- src/components/score/score.css
- src/components/score/score.html
- src/components/score/score.js
- src/components/team-introduction/team-introduction.css
- src/components/team-introduction/team-introduction.html
- src/components/team-introduction/team-introduction.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #63
> design - Home페이지 간격 수정 및 기타 margin, padding값 등 수정

- src/components/main-button/main-button.css
- src/components/main-button/main-button.html
- src/components/main-button/main-button.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #76
> design : 메인페이지 버튼 컴포넌트 크기 수정 완료

- netlify/functions/api-proxy.js
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #79
> fix - 치지직 라이브 파라미터값 오류 수정

- src/components/score/score.js
- src/components/searchbar/search-Bar.css
- src/components/searchbar/search-Bar.js
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #82
> feat : 사용자 검색 기록 기능 추가 #82

- netlify/functions/api-proxy.js
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #84
> fix - 치지직 라이브 응답코드 처리 로직 수정

- netlify/functions/api-proxy.js
- src/components/live/live.js
- src/components/score/score.css
- src/components/score/score.js
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
하는 김에 치지직 라이브 에러도 같이 해결했습니다:)
resolves #87
> design - 검색 가이드 이미지 로직 수정

- src/components/score-detail/score-detail.js
- src/services/api.js
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
design - 전적상세 컴포넌트 디자인 및 오류 수정
resolves #47
> design - 전적상세 컴포넌트 디자인 및 오류 수정

- src/components/score-detail/score-detail.css
- src/components/score-detail/score-detail.js
> fix : userDetail기능 수정

- netlify/functions/api-proxy.js
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #96
> fix - 상세전적 api 로직 예외처리 추가

- src/components/main-visual/main-visual.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #100
> design : 메인비주얼 텍스트 css 수정 완료
